[package]
name = "baker-link-env"
version = "0.2.1"
edition = "2021"
build = "build.rs"

[build-dependencies]
winres = "0.1"

[dependencies]
dioxus = { version = "0.7.1" }
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
env_logger = "0.11.3"
rfd = "0.14.1"
cargo-generate = "0.23"
anyhow = "1.0.86"
base64 = "0.22"
chrono = "0.4.38"
dirs = "5"
open = "5.3.0"
image = { version = "0.25", default-features = false, features = ["png"] }
probe-rs-tools = { path = "external/probe-rs/probe-rs-tools" }
tokio = { version = "1", features = ["rt", "time", "sync"] }
tokio-util = "0.7"
time = "0.3"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
