name: Build & Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            package-type: msi
          - os: macos-latest
            package-type: dmg

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Dioxus CLI
        uses: taiki-e/install-action@v2
        with:
          tool: dioxus-cli

      - name: Bundle
        run: dx bundle --release --package-types ${{ matrix.package-type }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
